name: Public bug issue
description: File a report about potential bugs you find.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: []
assignees:
  - pvj
body:
  - type: markdown
    attributes:
      value: |
        Please take your time to fill out each field with attention. Consult with [BER documentation](https://rtfm.ber.run) for any help!
  - type: textarea
    id: actual-what-happened
    attributes:
      label: What happened?
      description: Write a short summary in a step-by-step format. Feel free to share videos or images.
      placeholder: Tell us what you see!
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected-what-happened
    attributes:
      label: What was your expectation?
      description: Please describe the difference between reality and expectations
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Accept BER Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://https://github.com/berbyte/ber-os/blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
